#!/usr/bin/python3
import psycopg2
import login

print('Content-type:text/html\n\n')
print('<!DOCTYPE html>')
print('<html>')
print('<head>')
print('<title>ProjetoBD</title>')
print('<link rel = "stylesheet" type = "text/css" href = "./css/main.css"')
print('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
print('<meta charset="UTF-8">')
print('</head>')

connection = None
try:
    connection = psycopg2.connect(login.credentials)
    
    print('<body>')
    print('<header class="cima">')
    print('<main>')
    print('<div class="header1">')
    print('<div class="logo-bd">')
    print('<img src="./img/bd-logo.png">')
    print('</div>')
    print('<div class="logo-ist">')
    print('<img src="./img/ist-logo.png">')
    print('</div>')
    print('</div>')
    print('</main>')
    print('</header>')
    print('<div class="box-degrade">')
    print('<div class="content">')
    print('<div class="col-4">')
    print('<h3>Customer Manager</h3>')
    print('<ul>')
    print('<li>')
    print('<a href="./reg_cli.cgi">New Customer</a>')
    print('</li>')
    print('<li>')
    print('<a href="./rem_cli.cgi">Remove Customer</a>')
    print('</li>')
    print('</ul>')
    print('</div>')
    print('<div class="col-4-b">')
    print('<h3>Supplier Manager</h3>')
    print('<ul>')
    print('<li>')
    print('<a href="./add_supplier.cgi">New Supplier</a>')
    print('</li>')
    print('<li>')
    print('<a href="./remove_supplier.cgi">Remove Supplier</a>')
    print('</li>')
    print('</ul>')
    print('</div>')
    print('<div class="col-4">')
    print('<h3>Product Manager</h3>')
    print('<ul>')
    print('<li>')
    print('<a href="./change_price.cgi">Change Price</a>')
    print('</li>')
    print('<li>')
    print('<a href="./change_descr.cgi">Change Description</a>')
    print('</li>')
    print('<li>')
    print('<a href="./remove_prod.cgi">Remove Product</a>')
    print('</li>')
    print('</ul>')
    print('</div>')
    print('<div class="col-4-b">')
    print('<h3>Order Manager</h3>')
    print('<ul>')
    print('<li>')
    print('<a href="./new_order.cgi">Make an Order</a>')
    print('</li>')
    print('<li>')
    print('<a href="./pay_order.cgi">Pay an Order</a>')
    print('</li>')
    print('</ul>')
    print('</div>')
    print('</div>')
    print('</div>')

except Exception as e:
    print('<h1>An error occurred.</h1>')
    print('<p>{}</p>'.format(e))
finally:
	if connection is not None:
		connection.close()
print('</body>')
print('</html>')
