#!/usr/bin/python3

print("Content-type:text/html\n\n")
print("<!DOCTYPE html>")
print("<html>")
print("  <head>")
print('    <link rel = "stylesheet" type = "text/css" href = "./css/main.css">')
print("    <title>ProjetoBD</title>")
print('    <meta name="viewport" content="width=device-width, initial-scale=1.0">')
print("    <style>")
print("        .successful h3 {")
print("            color: white;")
print("            font-size: 50px;")
print("        }")
print("        .successful {")
print("          display: flex;")
print("          width: 100%;")
print("          position: relative;")
print("          float: left;")
print("          text-align: center;")
print("          justify-content: center;")
print("          align-items: center;")
print("        }")
print("    </style>")
print("  </head>")
print("  <body>")
print('    <header class="cima">')
print("        <main>")
print('            <div class="header1">')
print('                <div class="logo-bd">')
print('                    <img src="./img/bd-logo.png" >')
print("                </div>")
print('                <div class="logo-ist">')
print('                    <img src="./img/ist-logo.png" >')
print("                </div>")
print("            </div>")
print("        </main>")
print("    </header>")
print('      <div class="successful">')
print('        <h3>SUCCESSFUL OPERATION!</h3>')
print("      </div>")
print("")
print("    <script>")
print("")
print("        function redirectToPage() {")
print('          window.location.href = "./home_page.cgi";')
print("        }")
print("")
print("        setTimeout(redirectToPage, 5000);")
print("      </script>")
print("  </body>")
print("</html>")
